language: julia
os:
  - linux
julia:
  - 1.0
  - 1.2
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
  - julia: nightly
script: dash test.sh
after_success: julia --project=coverage/ coverage/submit.jl
